apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/quaggy/tekton-reversewords:17ba2b50a7a9afcffd2684d27234fb2470132a95
        env:
        - name: RELEASE
          value: "Stage Release"
        - $patch: replace
