apiVersion: apps/v1
kind: Deployment
metadata:
  name: reversewords
  labels:
    app: reversewords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reversewords
  template:
    metadata:
      labels:
        app: reversewords
    spec:
      containers:
      - name: reversewords
        image: quay.io/mavazque/tekton-reversewords:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: RELEASE
          value: "Base release"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 15
