apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/quaggy/tekton-reversewords:11f83344dfbb8dfa31ead0b418231413d3960b56
        env:
        - name: RELEASE
          value: "Stage Release"
        - $patch: replace
